version: '3.0'

services:
  kong_database:
    image: postgres
    container_name: kong_database_container
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kong
    ports:
      - 5432
    networks:
      - kong_net
    restart: always

  kong_migration:
    image: kong/kong-gateway:3.2.2.1
    container_name: kong_migration_container
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong_database
      - KONG_PG_PASSWORD=kong
    networks:
      - kong_net
    command: kong migrations bootstrap
    depends_on:
      - kong_database
  
  kong_gateway:
    image: kong/kong-gateway:3.2.2.1
    container_name: kong_gateway_container
    networks:
      - kong_net
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong_database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong

      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr

      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_GUI_URL=http://localhost:8002
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
      - 8002:8002
      - 8445:8445
      - 8003:8003
      - 8004:8004
    depends_on:
      - kong_database
networks:    
  kong_net:
    driver: bridge