version: '3'

services:
  gateway:
    image: kong/kong-gateway:3.2.2.1
    volumes:
      - ./kong.yaml:/kong/config/kong.yaml:ro
    container_name: kong_gateway_container
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/kong/config/kong.yaml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr 
      - KONG_ADMIN_LISTEN=0.0.0.0:8001 
      - KONG_ADMIN_GUI_URL=http://localhost:9002 
    ports:
      - 9000:8000
      - 9443:8443
      - 9001:8001
      - 9444:8444
      - 9002:8002
      - 9445:8445
      - 9003:8003
      - 9004:8004
